name: Drabir Here
favicon: null
layout_spectrum: 0.30162
typography_spectrum: 0.19474
title: Drabir Here
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-50843740-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2790b0'
    - '#353432'
    - '#4e4d4a'
    - '#94ba65'
    - '#769055'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
