typography_spectrum: 0.62274
color:
  brandColors:
    - '#E3E4DF'
    - '#000100'
    - '#7C9C3B'
    - '#3D5732'
    - '#A3B36A'
  brandStrength: 0.390765
  lightness: 0.375
  saturation: 0.515765
  rhythmicContrast: 0.5
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/d4a5ec81-93ba-45d3-b027-8ea6b143c7ed.png
  type: null
  appId: '104110772971734'
layout_spectrum: 0.9988
analytics:
  google: UA-50843740-2
  facebook: '1042066719222747'
  twitter: null
author:
  name: Drabir
  email: drabir@gmail.com
  url: facebook.com/drabir
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a902dfba-1263-48b0-9a60-d77b1d3f4923.png
name: Drabir Here
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dfd13628-e8c9-4101-a8f1-ca857106d3ae.png
title: Parenting | Cycling | Marketing
purpose: []
